n1 =int( input(" digite um numero inteiro: "))
print(n1)
print(type(n1))
n2 =float( input(" digite um numero real': "))
print(n2)
print(type(n2))
n3 =str( input(" digite alguma coisa: "))
print(n3)
print(type(n3))
